name: Stylecheck

on:
  push:
    branches:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  stylecheck:
    runs-on: ubuntu-24.04

    steps:
    - name: Clone
      uses: actions/checkout@v7

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install dependencies
      run: |
        pip install black

    - name: run stylecheck
      run: |
        python -m black --check --diff .
