name: 'Install Specialised Amulet-Resource-Pack'
description: 'Build, publish and install this library specialised for the installed compiler. Requires Python, build and twine.'
inputs:
  twine-username:
    description: 'The twine username'
    required: true
  twine-password:
    description: 'The twine password'
    required: true
  compiler-specifier:
    description: 'The PEP 440 version specifier for the compiler library'
    required: true
  resource-pack-specifier:
    description: 'The PEP 440 version specifier for the Resource-Pack library'
    required: true
outputs:
  version:
    description: "The version number of the installed library."
    value: ${{ steps.get-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.twine-username }}" ]; then
          echo "twine-username is empty"
          exit 1
        fi

        if [ -z "${{ inputs.twine-password }}" ]; then
          echo "twine-password is empty"
          exit 1
        fi

        if [ -z "${{ inputs.compiler-specifier }}" ]; then
          echo "compiler-specifier is empty"
          exit 1
        fi
        
        if [ -z "${{ inputs.resource-pack-specifier }}" ]; then
          echo "resource-pack-specifier is empty"
          exit 1
        fi

    - name: Install Prebuilt
      id: install
      shell: bash
      continue-on-error: true
      run: |
        python -m pip install --only-binary amulet-resource-pack amulet-compiler-version${{ inputs.compiler-specifier }} amulet-resource-pack${{ inputs.resource-pack-specifier }}

    - name: Build
      if: steps.install.outcome == 'failure'
      shell: bash
      env:
        AMULET_FREEZE_COMPILER: 1
      run: |
        python -m build --wheel "${{ github.action_path }}"/../../..

    - name: Publish
      if: steps.install.outcome == 'failure'
      shell: bash
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-password }}
      run: |
        twine upload "${{ github.action_path }}"/../../../dist/* --skip-existing

    - name: Install
      if: steps.install.outcome == 'failure'
      shell: bash
      run: |
        python -m pip install "${{ github.action_path }}"/../../../dist/amulet_resource_pack-*.whl

    - name: Get __version__
      id: get-version
      shell: bash
      run: |
        version=$(python -c "import amulet.resource_pack; print(amulet.resource_pack.__version__)")
        echo "version=$version" >> "$GITHUB_OUTPUT"
