# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
        os: [ macos-14, windows-latest ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Clone Amulet-Compiler-Version
      uses: actions/checkout@v4
      with:
        repository: 'Amulet-Team/Amulet-Compiler-Version'
        ref: '3.0'
        path: 'lib/Amulet-Compiler-Version'

    - name: Install Amulet-Compiler-Version
      uses: ./lib/Amulet-Compiler-Version/.github/actions/install
      with:
        twine-username: ${{ secrets.PYPI_USERNAME }}
        twine-password: ${{ secrets.AMULET_COMPILER_VERSION_PYPI_PASSWORD }}

    - name: Build SDist
      run: |
        python -m build --sdist .

    - name: Build Wheel
      env:
        AMULET_FREEZE_COMPILER: 1
      run: |
        python -m build --wheel .

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_RESOURCE_PACK_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
