name: Unittests

on:
  push:
    branches:
      - master
      - main
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  unittests:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025-vs2026, python-version: '3.14', architecture: x64 }
          - { os: windows-11-vs2026-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15-intel, python-version: '3.14', architecture: x64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }
          - { os: ubuntu-24.04, python-version: '3.14', architecture: x64 }

    runs-on: ${{ matrix.cfg.os }}
    timeout-minutes: 45
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v7
      with:
        submodules: 'true'

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Build (Windows/MacOS)
      if: runner.os != 'Linux'
      run: |
        pip install build
        python -m build .
        
    - name: Build (Linux)
      if: runner.os == 'Linux'
      uses: pypa/cibuildwheel@v4.1
      with:
        output-dir: dist
        only: "cp314-manylinux_x86_64"

    - name: Install
      run: |
        pip install "$(ls dist/*.whl | head -n 1)"

    - name: Compile Tests
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install "$(ls dist/*.whl | head -n 1)[dev]"
        python tools/compile_tests.py

    - name: Test with unittest
      run: python -m unittest discover -v -s tests
