name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { os: windows-2025-vs2026, python-version: '3.14', architecture: x64 }
          - { os: windows-11-vs2026-arm, python-version: '3.14', architecture: arm64 }
          - { os: macos-15, python-version: '3.14', architecture: arm64 }
          - { os: ubuntu-24.04, python-version: '3.14', architecture: x64 }

    runs-on: ${{ matrix.cfg.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v7

    - name: Setup cmake
      if: runner.os != 'Linux'
      uses: jwlawson/actions-setup-cmake@v2

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.cfg.python-version }}
        architecture: ${{ matrix.cfg.architecture }}

    - name: Build (Windows/MacOS)
      if: runner.os != 'Linux'
      run: |
        pip install build
        python -m build .
        
    - name: Build (Linux)
      if: runner.os == 'Linux'
      uses: pypa/cibuildwheel@v4.1
      with:
        output-dir: dist
        only: "cp314-manylinux_x86_64"

    - name: Install twine
      shell: bash
      run: |
        pip install twine

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_UTILS_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
