# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  release:
    types: [published]

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12' ]
        os: [ macos-14, windows-latest ]

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    steps:
    - name: Clone
      uses: actions/checkout@v4

    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        python-version: ${{ matrix.python-version }}
        username: ${{ secrets.PYPI_USERNAME }}
        compiler-version-password: ${{ secrets.AMULET_COMPILER_VERSION_PYPI_PASSWORD }}
        rest-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build SDist
      run: |
        python -m build --sdist .

    - name: Build Wheel
      env:
        AMULET_FREEZE_COMPILER: 1
      run: |
        python -m build --wheel .

    - name: Publish Amulet-Utils
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.AMULET_UTILS_PYPI_PASSWORD }}
      run: |
        twine upload dist/* --skip-existing
