name: 'Install Specialised Amulet-Game'
description: 'Build, publish and install this library specialised for the installed compiler. Requires Python, build and twine.'
inputs:
  twine-username:
    description: 'The twine username'
    required: true
  twine-password:
    description: 'The twine password'
    required: true
  compiler-specifier:
    description: 'The PEP 440 version specifier for the compiler library'
    required: true
  io-specifier:
    description: 'The PEP 440 version specifier for the io library'
    required: true
  nbt-specifier:
    description: 'The PEP 440 version specifier for the NBT library'
    required: true
  core-specifier:
    description: 'The PEP 440 version specifier for the Core library'
    required: true
  game-specifier:
    description: 'The PEP 440 version specifier for the Game library'
    required: true
outputs:
  version:
    description: "The version number of the installed library."
    value: ${{ steps.get-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        if [ -z "${{ inputs.twine-username }}" ]; then
          echo "twine-username is empty"
          exit 1
        fi

        if [ -z "${{ inputs.twine-password }}" ]; then
          echo "twine-password is empty"
          exit 1
        fi

        if [ -z "${{ inputs.compiler-specifier }}" ]; then
          echo "compiler-specifier is empty"
          exit 1
        fi

        if [ -z "${{ inputs.io-specifier }}" ]; then
          echo "io-specifier is empty"
          exit 1
        fi

        if [ -z "${{ inputs.nbt-specifier }}" ]; then
          echo "nbt-specifier is empty"
          exit 1
        fi

        if [ -z "${{ inputs.core-specifier }}" ]; then
          echo "core-specifier is empty"
          exit 1
        fi
        
        if [ -z "${{ inputs.game-specifier }}" ]; then
          echo "game-specifier is empty"
          exit 1
        fi

    - name: Install Prebuilt
      id: install
      shell: bash
      continue-on-error: true
      run: |
        python -m pip install --only-binary amulet-game amulet-compiler-version${{ inputs.compiler-specifier }} amulet-io${{ inputs.io-specifier }} amulet-nbt${{ inputs.nbt-specifier }} amulet-core${{ inputs.core-specifier }} amulet-game${{ inputs.game-specifier }}

    - name: Build
      if: steps.install.outcome == 'failure'
      shell: bash
      env:
        AMULET_FREEZE_COMPILER: 1
        AMULET_IO_REQUIREMENT: ${{ inputs.io-specifier }}
        AMULET_NBT_REQUIREMENT: ${{ inputs.nbt-specifier }}
        AMULET_CORE_REQUIREMENT: ${{ inputs.core-specifier }}
      run: |
        python -m build --wheel "${{ github.action_path }}"/../../..

    - name: Publish
      if: steps.install.outcome == 'failure'
      shell: bash
      env:
        TWINE_USERNAME: ${{ inputs.twine-username }}
        TWINE_PASSWORD: ${{ inputs.twine-password }}
      run: |
        twine upload "${{ github.action_path }}"/../../../dist/* --skip-existing

    - name: Install
      if: steps.install.outcome == 'failure'
      shell: bash
      run: |
        python -m pip install "${{ github.action_path }}"/../../../dist/amulet_game-*.whl

    - name: Get __version__
      id: get-version
      shell: bash
      run: |
        version=$(python -c "import amulet.game; print(amulet.game.__version__)")
        echo "version=$version" >> "$GITHUB_OUTPUT"
